//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="ServiceReference1.BankWS")]
    public interface BankWS {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento nome no namespace  não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BankWS/consultUserRequest", ReplyAction="http://ws/BankWS/consultUserResponse")]
        WindowsFormsApp1.ServiceReference1.consultUserResponse consultUser(WindowsFormsApp1.ServiceReference1.consultUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BankWS/consultUserRequest", ReplyAction="http://ws/BankWS/consultUserResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.consultUserResponse> consultUserAsync(WindowsFormsApp1.ServiceReference1.consultUserRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento nome no namespace  não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BankWS/saldoUserRequest", ReplyAction="http://ws/BankWS/saldoUserResponse")]
        WindowsFormsApp1.ServiceReference1.saldoUserResponse saldoUser(WindowsFormsApp1.ServiceReference1.saldoUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BankWS/saldoUserRequest", ReplyAction="http://ws/BankWS/saldoUserResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.saldoUserResponse> saldoUserAsync(WindowsFormsApp1.ServiceReference1.saldoUserRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento nome no namespace  não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BankWS/cadastrarUserRequest", ReplyAction="http://ws/BankWS/cadastrarUserResponse")]
        WindowsFormsApp1.ServiceReference1.cadastrarUserResponse cadastrarUser(WindowsFormsApp1.ServiceReference1.cadastrarUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BankWS/cadastrarUserRequest", ReplyAction="http://ws/BankWS/cadastrarUserResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.cadastrarUserResponse> cadastrarUserAsync(WindowsFormsApp1.ServiceReference1.cadastrarUserRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento oldNome no namespace  não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BankWS/alterCadastroRequest", ReplyAction="http://ws/BankWS/alterCadastroResponse")]
        WindowsFormsApp1.ServiceReference1.alterCadastroResponse alterCadastro(WindowsFormsApp1.ServiceReference1.alterCadastroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BankWS/alterCadastroRequest", ReplyAction="http://ws/BankWS/alterCadastroResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.alterCadastroResponse> alterCadastroAsync(WindowsFormsApp1.ServiceReference1.alterCadastroRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento nome no namespace  não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BankWS/depositoRequest", ReplyAction="http://ws/BankWS/depositoResponse")]
        WindowsFormsApp1.ServiceReference1.depositoResponse deposito(WindowsFormsApp1.ServiceReference1.depositoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BankWS/depositoRequest", ReplyAction="http://ws/BankWS/depositoResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.depositoResponse> depositoAsync(WindowsFormsApp1.ServiceReference1.depositoRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento nome no namespace  não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BankWS/saqueRequest", ReplyAction="http://ws/BankWS/saqueResponse")]
        WindowsFormsApp1.ServiceReference1.saqueResponse saque(WindowsFormsApp1.ServiceReference1.saqueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BankWS/saqueRequest", ReplyAction="http://ws/BankWS/saqueResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.saqueResponse> saqueAsync(WindowsFormsApp1.ServiceReference1.saqueRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultUser", Namespace="http://ws/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.consultUserRequestBody Body;
        
        public consultUserRequest() {
        }
        
        public consultUserRequest(WindowsFormsApp1.ServiceReference1.consultUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class consultUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nome;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string senha;
        
        public consultUserRequestBody() {
        }
        
        public consultUserRequestBody(string nome, string senha) {
            this.nome = nome;
            this.senha = senha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultUserResponse", Namespace="http://ws/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.consultUserResponseBody Body;
        
        public consultUserResponse() {
        }
        
        public consultUserResponse(WindowsFormsApp1.ServiceReference1.consultUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class consultUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public consultUserResponseBody() {
        }
        
        public consultUserResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saldoUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saldoUser", Namespace="http://ws/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.saldoUserRequestBody Body;
        
        public saldoUserRequest() {
        }
        
        public saldoUserRequest(WindowsFormsApp1.ServiceReference1.saldoUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class saldoUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nome;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string senha;
        
        public saldoUserRequestBody() {
        }
        
        public saldoUserRequestBody(string nome, string senha) {
            this.nome = nome;
            this.senha = senha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saldoUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saldoUserResponse", Namespace="http://ws/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.saldoUserResponseBody Body;
        
        public saldoUserResponse() {
        }
        
        public saldoUserResponse(WindowsFormsApp1.ServiceReference1.saldoUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class saldoUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double @return;
        
        public saldoUserResponseBody() {
        }
        
        public saldoUserResponseBody(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cadastrarUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cadastrarUser", Namespace="http://ws/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.cadastrarUserRequestBody Body;
        
        public cadastrarUserRequest() {
        }
        
        public cadastrarUserRequest(WindowsFormsApp1.ServiceReference1.cadastrarUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class cadastrarUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nome;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string senha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string saldo;
        
        public cadastrarUserRequestBody() {
        }
        
        public cadastrarUserRequestBody(string nome, string senha, string saldo) {
            this.nome = nome;
            this.senha = senha;
            this.saldo = saldo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cadastrarUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cadastrarUserResponse", Namespace="http://ws/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.cadastrarUserResponseBody Body;
        
        public cadastrarUserResponse() {
        }
        
        public cadastrarUserResponse(WindowsFormsApp1.ServiceReference1.cadastrarUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class cadastrarUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public cadastrarUserResponseBody() {
        }
        
        public cadastrarUserResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class alterCadastroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="alterCadastro", Namespace="http://ws/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.alterCadastroRequestBody Body;
        
        public alterCadastroRequest() {
        }
        
        public alterCadastroRequest(WindowsFormsApp1.ServiceReference1.alterCadastroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class alterCadastroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string oldNome;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string newNome;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string oldSenha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string newSenha;
        
        public alterCadastroRequestBody() {
        }
        
        public alterCadastroRequestBody(string oldNome, string newNome, string oldSenha, string newSenha) {
            this.oldNome = oldNome;
            this.newNome = newNome;
            this.oldSenha = oldSenha;
            this.newSenha = newSenha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class alterCadastroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="alterCadastroResponse", Namespace="http://ws/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.alterCadastroResponseBody Body;
        
        public alterCadastroResponse() {
        }
        
        public alterCadastroResponse(WindowsFormsApp1.ServiceReference1.alterCadastroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class alterCadastroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public alterCadastroResponseBody() {
        }
        
        public alterCadastroResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class depositoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deposito", Namespace="http://ws/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.depositoRequestBody Body;
        
        public depositoRequest() {
        }
        
        public depositoRequest(WindowsFormsApp1.ServiceReference1.depositoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class depositoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double valor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nome;
        
        public depositoRequestBody() {
        }
        
        public depositoRequestBody(double valor, string nome) {
            this.valor = valor;
            this.nome = nome;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class depositoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="depositoResponse", Namespace="http://ws/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.depositoResponseBody Body;
        
        public depositoResponse() {
        }
        
        public depositoResponse(WindowsFormsApp1.ServiceReference1.depositoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class depositoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public depositoResponseBody() {
        }
        
        public depositoResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saqueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saque", Namespace="http://ws/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.saqueRequestBody Body;
        
        public saqueRequest() {
        }
        
        public saqueRequest(WindowsFormsApp1.ServiceReference1.saqueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class saqueRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double valor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nome;
        
        public saqueRequestBody() {
        }
        
        public saqueRequestBody(double valor, string nome) {
            this.valor = valor;
            this.nome = nome;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saqueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saqueResponse", Namespace="http://ws/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.saqueResponseBody Body;
        
        public saqueResponse() {
        }
        
        public saqueResponse(WindowsFormsApp1.ServiceReference1.saqueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class saqueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public saqueResponseBody() {
        }
        
        public saqueResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BankWSChannel : WindowsFormsApp1.ServiceReference1.BankWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankWSClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference1.BankWS>, WindowsFormsApp1.ServiceReference1.BankWS {
        
        public BankWSClient() {
        }
        
        public BankWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.consultUserResponse WindowsFormsApp1.ServiceReference1.BankWS.consultUser(WindowsFormsApp1.ServiceReference1.consultUserRequest request) {
            return base.Channel.consultUser(request);
        }
        
        public string consultUser(string nome, string senha) {
            WindowsFormsApp1.ServiceReference1.consultUserRequest inValue = new WindowsFormsApp1.ServiceReference1.consultUserRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.consultUserRequestBody();
            inValue.Body.nome = nome;
            inValue.Body.senha = senha;
            WindowsFormsApp1.ServiceReference1.consultUserResponse retVal = ((WindowsFormsApp1.ServiceReference1.BankWS)(this)).consultUser(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.consultUserResponse> WindowsFormsApp1.ServiceReference1.BankWS.consultUserAsync(WindowsFormsApp1.ServiceReference1.consultUserRequest request) {
            return base.Channel.consultUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.consultUserResponse> consultUserAsync(string nome, string senha) {
            WindowsFormsApp1.ServiceReference1.consultUserRequest inValue = new WindowsFormsApp1.ServiceReference1.consultUserRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.consultUserRequestBody();
            inValue.Body.nome = nome;
            inValue.Body.senha = senha;
            return ((WindowsFormsApp1.ServiceReference1.BankWS)(this)).consultUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.saldoUserResponse WindowsFormsApp1.ServiceReference1.BankWS.saldoUser(WindowsFormsApp1.ServiceReference1.saldoUserRequest request) {
            return base.Channel.saldoUser(request);
        }
        
        public double saldoUser(string nome, string senha) {
            WindowsFormsApp1.ServiceReference1.saldoUserRequest inValue = new WindowsFormsApp1.ServiceReference1.saldoUserRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.saldoUserRequestBody();
            inValue.Body.nome = nome;
            inValue.Body.senha = senha;
            WindowsFormsApp1.ServiceReference1.saldoUserResponse retVal = ((WindowsFormsApp1.ServiceReference1.BankWS)(this)).saldoUser(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.saldoUserResponse> WindowsFormsApp1.ServiceReference1.BankWS.saldoUserAsync(WindowsFormsApp1.ServiceReference1.saldoUserRequest request) {
            return base.Channel.saldoUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.saldoUserResponse> saldoUserAsync(string nome, string senha) {
            WindowsFormsApp1.ServiceReference1.saldoUserRequest inValue = new WindowsFormsApp1.ServiceReference1.saldoUserRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.saldoUserRequestBody();
            inValue.Body.nome = nome;
            inValue.Body.senha = senha;
            return ((WindowsFormsApp1.ServiceReference1.BankWS)(this)).saldoUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.cadastrarUserResponse WindowsFormsApp1.ServiceReference1.BankWS.cadastrarUser(WindowsFormsApp1.ServiceReference1.cadastrarUserRequest request) {
            return base.Channel.cadastrarUser(request);
        }
        
        public bool cadastrarUser(string nome, string senha, string saldo) {
            WindowsFormsApp1.ServiceReference1.cadastrarUserRequest inValue = new WindowsFormsApp1.ServiceReference1.cadastrarUserRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.cadastrarUserRequestBody();
            inValue.Body.nome = nome;
            inValue.Body.senha = senha;
            inValue.Body.saldo = saldo;
            WindowsFormsApp1.ServiceReference1.cadastrarUserResponse retVal = ((WindowsFormsApp1.ServiceReference1.BankWS)(this)).cadastrarUser(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.cadastrarUserResponse> WindowsFormsApp1.ServiceReference1.BankWS.cadastrarUserAsync(WindowsFormsApp1.ServiceReference1.cadastrarUserRequest request) {
            return base.Channel.cadastrarUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.cadastrarUserResponse> cadastrarUserAsync(string nome, string senha, string saldo) {
            WindowsFormsApp1.ServiceReference1.cadastrarUserRequest inValue = new WindowsFormsApp1.ServiceReference1.cadastrarUserRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.cadastrarUserRequestBody();
            inValue.Body.nome = nome;
            inValue.Body.senha = senha;
            inValue.Body.saldo = saldo;
            return ((WindowsFormsApp1.ServiceReference1.BankWS)(this)).cadastrarUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.alterCadastroResponse WindowsFormsApp1.ServiceReference1.BankWS.alterCadastro(WindowsFormsApp1.ServiceReference1.alterCadastroRequest request) {
            return base.Channel.alterCadastro(request);
        }
        
        public bool alterCadastro(string oldNome, string newNome, string oldSenha, string newSenha) {
            WindowsFormsApp1.ServiceReference1.alterCadastroRequest inValue = new WindowsFormsApp1.ServiceReference1.alterCadastroRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.alterCadastroRequestBody();
            inValue.Body.oldNome = oldNome;
            inValue.Body.newNome = newNome;
            inValue.Body.oldSenha = oldSenha;
            inValue.Body.newSenha = newSenha;
            WindowsFormsApp1.ServiceReference1.alterCadastroResponse retVal = ((WindowsFormsApp1.ServiceReference1.BankWS)(this)).alterCadastro(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.alterCadastroResponse> WindowsFormsApp1.ServiceReference1.BankWS.alterCadastroAsync(WindowsFormsApp1.ServiceReference1.alterCadastroRequest request) {
            return base.Channel.alterCadastroAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.alterCadastroResponse> alterCadastroAsync(string oldNome, string newNome, string oldSenha, string newSenha) {
            WindowsFormsApp1.ServiceReference1.alterCadastroRequest inValue = new WindowsFormsApp1.ServiceReference1.alterCadastroRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.alterCadastroRequestBody();
            inValue.Body.oldNome = oldNome;
            inValue.Body.newNome = newNome;
            inValue.Body.oldSenha = oldSenha;
            inValue.Body.newSenha = newSenha;
            return ((WindowsFormsApp1.ServiceReference1.BankWS)(this)).alterCadastroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.depositoResponse WindowsFormsApp1.ServiceReference1.BankWS.deposito(WindowsFormsApp1.ServiceReference1.depositoRequest request) {
            return base.Channel.deposito(request);
        }
        
        public bool deposito(double valor, string nome) {
            WindowsFormsApp1.ServiceReference1.depositoRequest inValue = new WindowsFormsApp1.ServiceReference1.depositoRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.depositoRequestBody();
            inValue.Body.valor = valor;
            inValue.Body.nome = nome;
            WindowsFormsApp1.ServiceReference1.depositoResponse retVal = ((WindowsFormsApp1.ServiceReference1.BankWS)(this)).deposito(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.depositoResponse> WindowsFormsApp1.ServiceReference1.BankWS.depositoAsync(WindowsFormsApp1.ServiceReference1.depositoRequest request) {
            return base.Channel.depositoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.depositoResponse> depositoAsync(double valor, string nome) {
            WindowsFormsApp1.ServiceReference1.depositoRequest inValue = new WindowsFormsApp1.ServiceReference1.depositoRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.depositoRequestBody();
            inValue.Body.valor = valor;
            inValue.Body.nome = nome;
            return ((WindowsFormsApp1.ServiceReference1.BankWS)(this)).depositoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.saqueResponse WindowsFormsApp1.ServiceReference1.BankWS.saque(WindowsFormsApp1.ServiceReference1.saqueRequest request) {
            return base.Channel.saque(request);
        }
        
        public bool saque(double valor, string nome) {
            WindowsFormsApp1.ServiceReference1.saqueRequest inValue = new WindowsFormsApp1.ServiceReference1.saqueRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.saqueRequestBody();
            inValue.Body.valor = valor;
            inValue.Body.nome = nome;
            WindowsFormsApp1.ServiceReference1.saqueResponse retVal = ((WindowsFormsApp1.ServiceReference1.BankWS)(this)).saque(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.saqueResponse> WindowsFormsApp1.ServiceReference1.BankWS.saqueAsync(WindowsFormsApp1.ServiceReference1.saqueRequest request) {
            return base.Channel.saqueAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.saqueResponse> saqueAsync(double valor, string nome) {
            WindowsFormsApp1.ServiceReference1.saqueRequest inValue = new WindowsFormsApp1.ServiceReference1.saqueRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.saqueRequestBody();
            inValue.Body.valor = valor;
            inValue.Body.nome = nome;
            return ((WindowsFormsApp1.ServiceReference1.BankWS)(this)).saqueAsync(inValue);
        }
    }
}
